# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 776)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/icon sa babaw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon_withnames = QtWidgets.QWidget(self.centralwidget)
        self.icon_withnames.setGeometry(QtCore.QRect(-10, -10, 251, 791))
        self.icon_withnames.setStyleSheet("QWidget{\n"
"background-color:rgb(236,236,236);\n"
"cursor: pointer;\n"
"border: none;\n"
"border-radius: 20px 20px 0px 0px; \n"
"}\n"
"\n"
"QPushButton{\n"
"color:white;\n"
"text-align:center;\n"
"height:55px;\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: rgb(0, 122, 255);\n"
"\n"
"}")
        self.icon_withnames.setObjectName("icon_withnames")
        self.dashboard_2 = QtWidgets.QPushButton(self.icon_withnames)
        self.dashboard_2.setGeometry(QtCore.QRect(40, 160, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        self.dashboard_2.setFont(font)
        self.dashboard_2.setStyleSheet("QPushButton{\n"
"color: rgb(12,18,12);\n"
"text-align: left;\n"
"border: none;\n"
"height:30px;\n"
"padding-left: 10px;\n"
"\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboard_2.setIcon(icon1)
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setAutoExclusive(True)
        self.dashboard_2.setObjectName("dashboard_2")
        self.designs_2 = QtWidgets.QPushButton(self.icon_withnames)
        self.designs_2.setGeometry(QtCore.QRect(40, 220, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.designs_2.setFont(font)
        self.designs_2.setStyleSheet("QPushButton{\n"
"color: rgb(12,18,12);\n"
"text-align: left;\n"
"border: none;\n"
"height:30px;\n"
"padding-left: 10px;\n"
"\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/design.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.designs_2.setIcon(icon2)
        self.designs_2.setCheckable(True)
        self.designs_2.setAutoExclusive(True)
        self.designs_2.setObjectName("designs_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.icon_withnames)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 700, 181, 28))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"color: rgb(12,18,12);\n"
"text-align: left;\n"
"border: none;\n"
"height:30px;\n"
"padding-left: 10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius: 10px;\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: rgb(0, 122, 255);\n"
"font-weight: bold;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Log out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setAutoExclusive(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.employees_2 = QtWidgets.QPushButton(self.icon_withnames)
        self.employees_2.setGeometry(QtCore.QRect(40, 280, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.employees_2.setFont(font)
        self.employees_2.setStyleSheet("QPushButton{\n"
"color: rgb(12,18,12);\n"
"text-align: left;\n"
"border: none;\n"
"height:30px;\n"
"padding-left: 10px;\n"
"\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/employee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.employees_2.setIcon(icon4)
        self.employees_2.setCheckable(True)
        self.employees_2.setAutoExclusive(True)
        self.employees_2.setObjectName("employees_2")
        self.mediafiles = QtWidgets.QPushButton(self.icon_withnames)
        self.mediafiles.setGeometry(QtCore.QRect(40, 340, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.mediafiles.setFont(font)
        self.mediafiles.setStyleSheet("QPushButton{\n"
"color: rgb(12,18,12);\n"
"text-align: left;\n"
"border: none;\n"
"height:30px;\n"
"padding-left: 10px;\n"
"\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/media files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mediafiles.setIcon(icon5)
        self.mediafiles.setCheckable(True)
        self.mediafiles.setAutoExclusive(True)
        self.mediafiles.setObjectName("mediafiles")
        self.label_5 = QtWidgets.QLabel(self.icon_withnames)
        self.label_5.setGeometry(QtCore.QRect(110, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Inter Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;\n"
"color: black;\n"
"background-color: none;")
        self.label_5.setObjectName("label_5")
        self.sales_2 = QtWidgets.QPushButton(self.icon_withnames)
        self.sales_2.setGeometry(QtCore.QRect(40, 400, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.sales_2.setFont(font)
        self.sales_2.setStyleSheet("QPushButton{\n"
"color: rgb(12,18,12);\n"
"text-align: left;\n"
"border: none;\n"
"height:30px;\n"
"padding-left: 10px;\n"
"\n"
"background-color: none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: white;\n"
"color: black;\n"
"font-weight: bold;\n"
"\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/sales.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sales_2.setIcon(icon6)
        self.sales_2.setCheckable(True)
        self.sales_2.setAutoExclusive(True)
        self.sales_2.setObjectName("sales_2")
        self.label = QtWidgets.QLabel(self.icon_withnames)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Icons/icon sa babaw.png"))
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(250, 0, 911, 771))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.widget_2 = QtWidgets.QWidget(self.dashboard)
        self.widget_2.setGeometry(QtCore.QRect(50, 80, 791, 121))
        self.widget_2.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;")
        self.widget_2.setObjectName("widget_2")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(590, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background: none;\n"
"border: none;\n"
"color: rgb(12,18,12);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(110, 30, 351, 81))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(12,18,12);\n"
"background: none;\n"
"border: none;\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 91, 81))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("\n"
"background: none;\n"
"border: none;\n"
"color: rgb(184,3,1);")
        self.label_9.setObjectName("label_9")
        self.widget_4 = QtWidgets.QWidget(self.dashboard)
        self.widget_4.setGeometry(QtCore.QRect(50, 220, 241, 131))
        self.widget_4.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;")
        self.widget_4.setObjectName("widget_4")
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_4)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background: none;\n"
"border: none;\n"
"color: Black;")
        self.label_17.setObjectName("label_17")
        self.label_25 = QtWidgets.QLabel(self.dashboard)
        self.label_25.setGeometry(QtCore.QRect(50, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("border: none;\n"
"color:#1F384C;\n"
"background-color: none;")
        self.label_25.setObjectName("label_25")
        self.widget_5 = QtWidgets.QWidget(self.dashboard)
        self.widget_5.setGeometry(QtCore.QRect(320, 220, 251, 131))
        self.widget_5.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_20 = QtWidgets.QLabel(self.widget_5)
        self.label_20.setGeometry(QtCore.QRect(20, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_5)
        self.label_21.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_21.setObjectName("label_21")
        self.widget_6 = QtWidgets.QWidget(self.dashboard)
        self.widget_6.setGeometry(QtCore.QRect(600, 220, 241, 131))
        self.widget_6.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;")
        self.widget_6.setObjectName("widget_6")
        self.label_22 = QtWidgets.QLabel(self.widget_6)
        self.label_22.setGeometry(QtCore.QRect(20, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_6)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_23.setObjectName("label_23")
        self.widget_7 = QtWidgets.QWidget(self.dashboard)
        self.widget_7.setGeometry(QtCore.QRect(50, 370, 391, 131))
        self.widget_7.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;")
        self.widget_7.setObjectName("widget_7")
        self.label_33 = QtWidgets.QLabel(self.widget_7)
        self.label_33.setGeometry(QtCore.QRect(20, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_7)
        self.label_34.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background: none;\n"
"border: none;\n"
"color: Black;")
        self.label_34.setObjectName("label_34")
        self.widget_8 = QtWidgets.QWidget(self.dashboard)
        self.widget_8.setGeometry(QtCore.QRect(460, 370, 381, 131))
        self.widget_8.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;")
        self.widget_8.setObjectName("widget_8")
        self.label_35 = QtWidgets.QLabel(self.widget_8)
        self.label_35.setGeometry(QtCore.QRect(20, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.widget_8)
        self.label_36.setGeometry(QtCore.QRect(20, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background: none;\n"
"border: none;\n"
"color: Black;")
        self.label_36.setObjectName("label_36")
        self.widget_10 = QtWidgets.QWidget(self.dashboard)
        self.widget_10.setGeometry(QtCore.QRect(50, 520, 791, 211))
        self.widget_10.setStyleSheet("background-color: rgb(236,236,236);\n"
"border-radius: 20px;")
        self.widget_10.setObjectName("widget_10")
        self.label_37 = QtWidgets.QLabel(self.widget_10)
        self.label_37.setGeometry(QtCore.QRect(10, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;\n"
"")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.widget_10)
        self.label_38.setGeometry(QtCore.QRect(50, 120, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background: none;\n"
"border: none;\n"
"color: Black;")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.widget_10)
        self.label_39.setGeometry(QtCore.QRect(110, 140, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.widget_10)
        self.label_40.setGeometry(QtCore.QRect(360, 120, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background: none;\n"
"border: none;\n"
"color: Black;")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.widget_10)
        self.label_41.setGeometry(QtCore.QRect(420, 140, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;\n"
"")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.widget_10)
        self.label_42.setGeometry(QtCore.QRect(320, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;\n"
"")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.widget_10)
        self.label_43.setGeometry(QtCore.QRect(650, 120, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background: none;\n"
"border: none;\n"
"color: Black;")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.widget_10)
        self.label_44.setGeometry(QtCore.QRect(610, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;\n"
"")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.widget_10)
        self.label_45.setGeometry(QtCore.QRect(710, 140, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background: none;\n"
"border: none;\n"
"color: black;\n"
"")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 791, 31))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;\n"
"color: black;\n"
"background-color: none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.dashboard)
        self.designs = QtWidgets.QWidget()
        self.designs.setObjectName("designs")
        self.tableWidget = QtWidgets.QTableWidget(self.designs)
        self.tableWidget.setGeometry(QtCore.QRect(50, 140, 811, 511))
        font = QtGui.QFont()
        font.setFamily("Inter")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("\n"
"background-color:white;\n"
"gridline-color: rgb(79, 79, 79);\n"
"selection-background-color: rgb(255, 172, 172);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(84, 84, 84))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(129, 129, 129))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        self.search_bar = QtWidgets.QLineEdit(self.designs)
        self.search_bar.setGeometry(QtCore.QRect(50, 80, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        self.search_bar.setFont(font)
        self.search_bar.setStyleSheet("color:black;\n"
"border:2px solid gray;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"background-color:rgb(237,237,237);\n"
"\n"
"padding: 5px;\n"
"border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px; \n"
"    border-top-right-radius: 0px; \n"
"    border-bottom-right-radius: 0px; ")
        self.search_bar.setText("")
        self.search_bar.setFrame(True)
        self.search_bar.setCursorPosition(0)
        self.search_bar.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.search_bar.setClearButtonEnabled(True)
        self.search_bar.setObjectName("search_bar")
        self.searchbutton = QtWidgets.QPushButton(self.designs)
        self.searchbutton.setGeometry(QtCore.QRect(760, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchbutton.setFont(font)
        self.searchbutton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.searchbutton.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 0px; /* Round top-left corner */\n"
"border-bottom-left-radius: 0px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.searchbutton.setCheckable(True)
        self.searchbutton.setObjectName("searchbutton")
        self.label_26 = QtWidgets.QLabel(self.designs)
        self.label_26.setGeometry(QtCore.QRect(50, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("border: none;\n"
"color:#1F384C;\n"
"background-color: none;")
        self.label_26.setObjectName("label_26")
        self.add_design_button = QtWidgets.QPushButton(self.designs)
        self.add_design_button.setGeometry(QtCore.QRect(50, 680, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.add_design_button.setFont(font)
        self.add_design_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_design_button.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.add_design_button.setCheckable(True)
        self.add_design_button.setObjectName("add_design_button")
        self.delete_design_button = QtWidgets.QPushButton(self.designs)
        self.delete_design_button.setGeometry(QtCore.QRect(710, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.delete_design_button.setFont(font)
        self.delete_design_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.delete_design_button.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.delete_design_button.setCheckable(True)
        self.delete_design_button.setObjectName("delete_design_button")
        self.update_design_button = QtWidgets.QPushButton(self.designs)
        self.update_design_button.setGeometry(QtCore.QRect(390, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.update_design_button.setFont(font)
        self.update_design_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.update_design_button.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.update_design_button.setCheckable(True)
        self.update_design_button.setObjectName("update_design_button")
        self.stackedWidget.addWidget(self.designs)
        self.employees = QtWidgets.QWidget()
        self.employees.setObjectName("employees")
        self.searchbutton_2 = QtWidgets.QPushButton(self.employees)
        self.searchbutton_2.setGeometry(QtCore.QRect(760, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchbutton_2.setFont(font)
        self.searchbutton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.searchbutton_2.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 0px; /* Round top-left corner */\n"
"border-bottom-left-radius: 0px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.searchbutton_2.setCheckable(True)
        self.searchbutton_2.setObjectName("searchbutton_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.employees)
        self.tableWidget_2.setGeometry(QtCore.QRect(50, 140, 811, 511))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("\n"
"background-color:white;\n"
"gridline-color: rgb(79, 79, 79);\n"
"selection-background-color: rgb(255, 172, 172);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(84, 84, 84))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        item.setFont(font)
        item.setBackground(QtGui.QColor(94, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        item.setFont(font)
        self.tableWidget_2.setItem(0, 0, item)
        self.search_bar_2 = QtWidgets.QLineEdit(self.employees)
        self.search_bar_2.setGeometry(QtCore.QRect(50, 80, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        self.search_bar_2.setFont(font)
        self.search_bar_2.setStyleSheet("color:black;\n"
"border:2px solid gray;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"background-color:rgb(237,237,237);\n"
"\n"
"padding: 5px;\n"
"border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px; \n"
"    border-top-right-radius: 0px; \n"
"    border-bottom-right-radius: 0px; ")
        self.search_bar_2.setText("")
        self.search_bar_2.setFrame(True)
        self.search_bar_2.setCursorPosition(0)
        self.search_bar_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.search_bar_2.setClearButtonEnabled(True)
        self.search_bar_2.setObjectName("search_bar_2")
        self.del_emp_button = QtWidgets.QPushButton(self.employees)
        self.del_emp_button.setGeometry(QtCore.QRect(710, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.del_emp_button.setFont(font)
        self.del_emp_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.del_emp_button.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.del_emp_button.setCheckable(True)
        self.del_emp_button.setObjectName("del_emp_button")
        self.label_27 = QtWidgets.QLabel(self.employees)
        self.label_27.setGeometry(QtCore.QRect(50, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border: none;\n"
"color:#1F384C;\n"
"background-color: none;")
        self.label_27.setObjectName("label_27")
        self.add_emp_button = QtWidgets.QPushButton(self.employees)
        self.add_emp_button.setGeometry(QtCore.QRect(50, 680, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.add_emp_button.setFont(font)
        self.add_emp_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.add_emp_button.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.add_emp_button.setCheckable(True)
        self.add_emp_button.setObjectName("add_emp_button")
        self.update_design_button_2 = QtWidgets.QPushButton(self.employees)
        self.update_design_button_2.setGeometry(QtCore.QRect(390, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.update_design_button_2.setFont(font)
        self.update_design_button_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.update_design_button_2.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.update_design_button_2.setCheckable(True)
        self.update_design_button_2.setObjectName("update_design_button_2")
        self.stackedWidget.addWidget(self.employees)
        self.media = QtWidgets.QWidget()
        self.media.setObjectName("media")
        self.label_4 = QtWidgets.QLabel(self.media)
        self.label_4.setGeometry(QtCore.QRect(190, 240, 541, 101))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.media)
        self.label_10.setGeometry(QtCore.QRect(170, 350, 571, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 0);\n"
"color: rgb(255, 170, 0);")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.media)
        self.sales = QtWidgets.QWidget()
        self.sales.setObjectName("sales")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.sales)
        self.tableWidget_3.setGeometry(QtCore.QRect(50, 80, 811, 571))
        self.tableWidget_3.setStyleSheet("\n"
"background-color:white;\n"
"gridline-color: rgb(79, 79, 79);\n"
"selection-background-color: rgb(255, 172, 172);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(8)
        self.tableWidget_3.setRowCount(23)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(84, 84, 84))
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        item.setFont(font)
        item.setBackground(QtGui.QColor(94, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Inter")
        item.setFont(font)
        self.tableWidget_3.setItem(0, 0, item)
        self.label_28 = QtWidgets.QLabel(self.sales)
        self.label_28.setGeometry(QtCore.QRect(50, 30, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border: none;\n"
"color:#1F384C;\n"
"background-color: none;")
        self.label_28.setObjectName("label_28")
        self.searchbutton_8 = QtWidgets.QPushButton(self.sales)
        self.searchbutton_8.setGeometry(QtCore.QRect(710, 680, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.searchbutton_8.setFont(font)
        self.searchbutton_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.searchbutton_8.setStyleSheet("background-color: rgb(184,3,1);\n"
"\n"
"color:#fff;\n"
"border-top-left-radius: 10px; /* Round top-left corner */\n"
"border-bottom-left-radius: 10px; /* Round bottom-left corner */\n"
"border-top-right-radius: 10px; /* No rounding for top-right corner */\n"
"border-bottom-right-radius: 10px; ")
        self.searchbutton_8.setCheckable(True)
        self.searchbutton_8.setObjectName("searchbutton_8")
        self.stackedWidget.addWidget(self.sales)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_8.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.dashboard_2.clicked.connect(self.stackedWidget.show) # type: ignore
        self.designs_2.clicked.connect(self.stackedWidget.show) # type: ignore
        self.employees_2.clicked.connect(self.stackedWidget.show) # type: ignore
        self.mediafiles.clicked.connect(self.stackedWidget.show) # type: ignore
        self.sales_2.clicked.connect(self.stackedWidget.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "  DRILAB"))
        self.dashboard_2.setText(_translate("MainWindow", "   Dashboard"))
        self.designs_2.setText(_translate("MainWindow", "   Designs"))
        self.pushButton_8.setText(_translate("MainWindow", "   Sign out"))
        self.employees_2.setText(_translate("MainWindow", "   Employees"))
        self.mediafiles.setText(_translate("MainWindow", "   Media Files"))
        self.label_5.setText(_translate("MainWindow", "DRILAB"))
        self.sales_2.setText(_translate("MainWindow", "   Sales"))
        self.label_7.setText(_translate("MainWindow", "TOTAL EARNINGS"))
        self.label_8.setText(_translate("MainWindow", "36,000"))
        self.label_9.setText(_translate("MainWindow", "₱"))
        self.label_16.setText(_translate("MainWindow", "TOTAL ITEMS"))
        self.label_17.setText(_translate("MainWindow", "50"))
        self.label_25.setText(_translate("MainWindow", "Business Dashboard"))
        self.label_20.setText(_translate("MainWindow", "ITEMS SOLD"))
        self.label_21.setText(_translate("MainWindow", "50"))
        self.label_22.setText(_translate("MainWindow", "EMPLOYEES"))
        self.label_23.setText(_translate("MainWindow", "50"))
        self.label_33.setText(_translate("MainWindow", "OUT OF STOCK"))
        self.label_34.setText(_translate("MainWindow", "50"))
        self.label_35.setText(_translate("MainWindow", "NEW DESIGNS"))
        self.label_36.setText(_translate("MainWindow", "50"))
        self.label_37.setText(_translate("MainWindow", "DESIGN NAME"))
        self.label_38.setText(_translate("MainWindow", "50"))
        self.label_39.setText(_translate("MainWindow", "pcs"))
        self.label_40.setText(_translate("MainWindow", "50"))
        self.label_41.setText(_translate("MainWindow", "pcs"))
        self.label_42.setText(_translate("MainWindow", "DESIGN NAME"))
        self.label_43.setText(_translate("MainWindow", "50"))
        self.label_44.setText(_translate("MainWindow", "DESIGN NAME"))
        self.label_45.setText(_translate("MainWindow", "pcs"))
        self.label_6.setText(_translate("MainWindow", "TOP SELLING DESIGNS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESIGN ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DESIGN NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SMALL"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MEDIUM"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "LARGE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EXTRA LARGE"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.search_bar.setPlaceholderText(_translate("MainWindow", "Search design name"))
        self.searchbutton.setText(_translate("MainWindow", "Search"))
        self.label_26.setText(_translate("MainWindow", "Designs"))
        self.add_design_button.setText(_translate("MainWindow", "ADD DESIGN"))
        self.delete_design_button.setText(_translate("MainWindow", "DELETE DESIGN"))
        self.update_design_button.setText(_translate("MainWindow", "UPDATE DESIGN"))
        self.searchbutton_2.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "EMPLOYEE ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "LAST NAME"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FIRST NAME"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CONTACT NO."))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "POSITION"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DATE STARTED"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.search_bar_2.setPlaceholderText(_translate("MainWindow", "Search employee"))
        self.del_emp_button.setText(_translate("MainWindow", "DELETE EMPLOYEE"))
        self.label_27.setText(_translate("MainWindow", "Employees"))
        self.add_emp_button.setText(_translate("MainWindow", "ADD EMPLOYEE"))
        self.update_design_button_2.setText(_translate("MainWindow", "UPDATE EMPLOYEE"))
        self.label_4.setText(_translate("MainWindow", "MEDIA FILES UNDER CONSTRUCTION"))
        self.label_10.setText(_translate("MainWindow", "UNDER CONSTRUCTION"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESIGN ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DESIGN NAME"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SMALL"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MEDIUM"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "LARGE"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EXTRA LARGE"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SOLD"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "EARNINGS"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_28.setText(_translate("MainWindow", "Sales"))
        self.searchbutton_8.setText(_translate("MainWindow", "ADD SALES"))

from Icons import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
